"""Compute & Model Assessor Subsystem — Backward-compatible facade module.

All implementation has been decomposed into modular components in ``harness.services.compute``.
This module re-exports the complete public interface for 100% backward compatibility.
"""

from __future__ import annotations

from harness.services.compute import (
    COMPUTE_ASSESSOR_SERVICE,
    AssessmentTrace,
    BaseProviderAdapter,
    ClaudeProviderAdapter,
    ComplexityDimension,
    ComplexityVector,
    ComputeAssessedEvent,
    ComputeAssessment,
    ComputeAssessorPlugin,
    ComputeAssessorService,
    ComputeEconomics,
    ComputeEconomicsEstimator,
    ComputeRouter,
    ComputeVisualBriefGenerator,
    DeepSeekProviderAdapter,
    DimensionalScorer,
    DynamicTrajectoryEscalator,
    FallbackLiteLLMAdapter,
    GLOBAL_PRICING_CATALOG,
    GeminiProviderAdapter,
    ModelPricingCatalog,
    ModelPricingRecord,
    ModelTier,
    OllamaProviderAdapter,
    OpenAIProviderAdapter,
    ProviderReasoningAdapter,
    ProviderReasoningRegistry,
    ScoringProfile,
    ScoringProfileName,
    ThinkingBudget,
    TrajectoryState,
)

__all__ = [
    "COMPUTE_ASSESSOR_SERVICE",
    "AssessmentTrace",
    "BaseProviderAdapter",
    "ClaudeProviderAdapter",
    "ComplexityDimension",
    "ComplexityVector",
    "ComputeAssessedEvent",
    "ComputeAssessment",
    "ComputeAssessorPlugin",
    "ComputeAssessorService",
    "ComputeEconomics",
    "ComputeEconomicsEstimator",
    "ComputeRouter",
    "ComputeVisualBriefGenerator",
    "DeepSeekProviderAdapter",
    "DimensionalScorer",
    "DynamicTrajectoryEscalator",
    "FallbackLiteLLMAdapter",
    "GLOBAL_PRICING_CATALOG",
    "GeminiProviderAdapter",
    "ModelPricingCatalog",
    "ModelPricingRecord",
    "ModelTier",
    "OllamaProviderAdapter",
    "OpenAIProviderAdapter",
    "ProviderReasoningAdapter",
    "ProviderReasoningRegistry",
    "ScoringProfile",
    "ScoringProfileName",
    "ThinkingBudget",
    "TrajectoryState",
]
